### ISSUE TITLE
Errors in String+Access.swift

### ISSUE THREAD

**Issue by multinerd** [stockx/PinEntryView#8]
`'init(_:)' is unavailable: CountableRange is now a Range. No need to convert any more.` on `substring` and `subscript` methods

**Comment by jeffaburt** [comment]
Hey there, thanks for reaching out! If you want to open up a pull request that fixes this issue, we'll be more than happy to check it out!

**Comment by multinerd** [comment]
Yea, I have a fix. Ill get right on it!

**Comment by multinerd** [comment]
PR: #9
